### ISSUE TITLE
Feature request : don't format quote

### ISSUE THREAD

**Issue by jvachez** [sunjw/jstoolnpp#101]
Hello,

It will be better is JSTool doesn't format quote. (onyl { } and ,)

I have simple quote for text (example : don't) so I must replace them by space if I want JSTool formats without problem.

**Comment by sunjw** [comment]
Could you give a sample?

**Comment by jvachez** [comment]
Yes some example for the text "Numéro d'O.F."

IDOF(O) = {
    OF(O) = {
        TXT(V) = Numéro d O.F.,
        VAL(I) = 49189
    },
}

OK with a space

IDOF(O) = {
    OF(O) = {
        TXT(V) = Numéro d 'O.F.,
                    VAL(I) = 49189
                },
            }


NOK with a quote a space has been added before the quote and tabulations are incorrects after because quote is formatted specially

**Comment by sunjw** [comment]
No "" around "Numéro d 'O.F." string? Doesn't look like valid JS or JSON.
