### ISSUE TITLE
Timstamp value impacts key on next element in JSON Viewer

### ISSUE THREAD

**Issue by FxProgrm** [sunjw/jstoolnpp#102]
Parsing the result of job submission json in JSToolNpp JSON Viewer fails to parse the key properly when the following situation is present.

'CreatedAt': datetime.datetime(2021, 2, 12, 18, 14, 26, tzinfo = tzlocal()),
 'Id': 'account-77qy6y',

You can see that when parsed the CreatedAt shows a value of datetime.datetime and the following key shows the ':)' which should be 'Id' but starts the key.  

Additionally,
Noticed when, the parsing of the json does not parse properly to provide the collapse points in the margin (CTL-ALT-M).

[sample.json.txt](https://github.com/sunjw/jstoolnpp/files/5973749/sample.json.txt)
![jstoolnpp-021221](https://user-images.githubusercontent.com/20388473/107808952-05513d00-6d30-11eb-9dbf-0bcbde82e407.png)

Thanks.

**Comment by sunjw** [comment]
Because this is JS not valid JSON, "datetime.datetime(2021, 2, 12, 18, 14, 26, tzinfo = tzlocal())" part can not be treated as a proper value.
