### ISSUE TITLE
Format Shortcut Alternative

### ISSUE THREAD

**Issue by DeeFeeCee** [sunjw/jstoolnpp#104]
Is there any way to change the shortcut from ctrl+alt+m to something that actually works? I've looked at the previous issues & it seems other apps can cause this shortcut to not function at all. But is it possible to tweak a line of the .dll to something else? e.g. ctrl+alt+f or something that can be typed with one hand?

Edit: Just discovered Shortcut Mapper accessible via Macros.

**Comment by sunjw** [comment]
Yes, you can change this shortcut in NPP.
