### ISSUE TITLE
"Í" character on hungarian keyboard layout

### ISSUE THREAD

**Issue by LukacsP** [sunjw/jstoolnpp#110]
Hello,

when i try to use JSTool for npp with a hungarian keyboard, pressing the "Í" key (https://en.wikipedia.org/wiki/%C3%8D) opens the js tree viewer. 
this means one cannot type "í" in notepad++ while this plugin is installed.

**Comment by sunjw** [comment]
Maybe you can change shortcut in Notepad++ menu. Not an issue from this plugin, I think.
