### ISSUE TITLE
Feature Request: (un)escape JSON

### ISSUE THREAD

**Issue by robross0606** [sunjw/jstoolnpp#112]
Would be great if this offered (un)escape JSON encoded as a string.  Similar in function to this: https://www.freeformatter.com/json-escape.html

**Comment by sunjw** [comment]
JSTool for Visual Studio Code has "Refresh JSON Tree View" command, and you can copy unescaped value from JSON tree context menu (right click node).

**Comment by sunjw** [comment]
https://github.com/sunjw/jstoolnpp/issues/82
