### ISSUE TITLE
[Feature Request] Validator function

### ISSUE THREAD

**Issue by dfs-** [sunjw/jstoolnpp#116]
I really love JSTool as it makes working with large JSON files a bliss.

However there is one feature it's kind of lacking as for my use case: a validator function. I often have to modify said JSON files by hand and so it happens that I make errors, adding a comma where it shouldn't be or leave one out. A validator function would let me find those errors fast and makes fixing them easy.

Right now I resort to copying my whole JSON to https://jsonformatter.curiousconcept.com/, uncheck the "Fix JSON" checkbox and then look up which errors are present according to RFC 8259 (as that is what most implementations seem to use). If this function would be included in JSTool it'd help me alot.

Thanks for considering the change!

**Comment by sunjw** [comment]
Sorry, no. Code editor (like Visual Studio Code) already have this function.
