### ISSUE TITLE
Feature request: Configurable shortcut keys.

### ISSUE THREAD

**Issue by paronix** [sunjw/jstoolnpp#118]
I'm already using CTRL+ALT+M as a shortcut for something else on my computer. Would it be possible to make the keyboard shortcuts for JSToolNPP configurable?

**Comment by paronix** [comment]
Nevermind! I've not had my coffee yet apparently ;-)

You can edit these in the shortcutmapper of NP++ itself.

**Comment by sunjw** [comment]
☕️
