### ISSUE TITLE
In Notepad++, after I use JSFormat, then the whole editor became Red which is not easy to recognize the text.

### ISSUE THREAD

**Issue by lapcca** [sunjw/jstoolnpp#121]
In Notepad++, after I use JSFormat, then the whole editor became Red which is not easy to recognize the text
![Untitled](https://user-images.githubusercontent.com/5364806/158920365-74448fbb-a920-40c9-9e4b-87d5eddd902b.png)
.

**Comment by sunjw** [comment]
Because it's not JSON string, and the red color is from N++'s syntax highlighting.
