### ISSUE TITLE
反馈:关于jsformat时,function中的var连续变量会换行.

### ISSUE THREAD

**Issue by eAtmApp** [sunjw/jstoolnpp#123]
function(){
    var a,b,c,d,e,f,g;
}
格式化后会变成
function () {
    var a,
    b,
    c,
    d,
    e,
    f,
    g;
}
这个能解决么,
或者能指点一下这部分源码具体在哪个位置,
我先找找看

**Comment by sunjw** [comment]
已知问题，大概率估计不会解决。

**Comment by eAtmApp** [comment]
> 已知问题，大概率估计不会解决。

		//if (StackTopEq(m_blockStack, JS_BLOCK) && !bHaveNewLine)
		if (StackTopEq(m_blockStack, JS_BLOCK) && !bHaveNewLine && (m_lineBuffer.size() < 4 || memcmp(m_lineBuffer.c_str(), "var ", 4) != 0))
		{
			PutToken(m_tokenA, string(""), strRight.append("\n")); // 如果是 {} 里的
		}
-_- 我自己改了下先将就用着.
