### ISSUE TITLE
[Feature Request]  curly braces on their own line option

### ISSUE THREAD

**Issue by Owyn** [sunjw/jstoolnpp#128]
current output:
```
fuunction(){
    // stuff
}

```

What I want:
```
fuunction()
{
    // stuff
}
```

**Comment by sunjw** [comment]
It used to have this feature, but removed in 1.2111.0. Because I cannot keep this feature in a good quality (cannot produce good output, and cannot find enough test cases).

**Comment by Owyn** [comment]
If you need reference how it could be done in good quality without issues - you could see https://github.com/beautify-web/js-beautify/

**Comment by sunjw** [comment]
Duplicated to #114
