### ISSUE TITLE
cannot access it in VS Code 1.72.2

### ISSUE THREAD

**Issue by tradrejoe** [sunjw/jstoolnpp#134]
After installing, I can't figure out how to access it in VS Code. I can't find it in the command pallete or left handside toolbar.

**Comment by tradrejoe** [comment]
Is it the JSON Sort command?

**Comment by sunjw** [comment]
All commands are in "command palette", following screenshot shows them:
<img width="849" alt="截屏2022-11-21 15 19 32" src="https://user-images.githubusercontent.com/846335/202988723-af9b1b2f-3984-43f5-9459-48909c7354fd.png">

![图片](https://user-images.githubusercontent.com/846335/202989472-d0da2149-80b5-45d2-8e94-7c8590df638e.png)
