### ISSUE TITLE
Jumping to proper location by selecting a node in tree view in multi-display PCs

### ISSUE THREAD

**Issue by Gholamalih** [sunjw/jstoolnpp#135]
I have three monitors, when my notepad++ is in monitor 1, I can not jump to proper location by selecting a node in the tree view. my main monitor is monitor 2. monitor 3 is OK .

**Comment by sunjw** [comment]
Not a JSTool plugin bug. I think you need to submit this bug to https://github.com/notepad-plus-plus/notepad-plus-plus

**Comment by Gholamalih** [comment]
In my opinion it's better you as the developer of JSTools, report this bug.
