### ISSUE TITLE
[bug] AltGr + J blocks typing of "í" letter (HU)

### ISSUE THREAD

**Issue by PizzaProgram** [sunjw/jstoolnpp#136]
# Keyboard shortcuts should **not be enabled** by default.

After installing this plugin, it makes it impossible to type a simple note under NP++, because every time someone is pressing the `[ í ]` or captial `[ Í ]` button on a 101 button keyboard (which are equal to [ AltGr + J or I] : 
- a Showmessage window is popping up with the message "Can not parse JSON"
- a JSON Viewer sidebar pops up,
- the letter í or Í is **not** added to the text.
- from there on every "í" letter goes into the sidebar's search box.

Or at least it should be possible to turn those OFF at the Option menu.
_(But it is a very difficult task, especially for average users, to find out what's happening, what is causing suddenly this behaviour! Not to mention how to prevent it.)_

**Comment by sunjw** [comment]
You can change it from NPP's shortcut management. I cannot give shortcut a option to enable or disable, simply because it is impossible for a NPP plugin.

**Comment by sunjw** [comment]
Duplicated to #48
