### ISSUE TITLE
Crash formatting JSON code

### ISSUE THREAD

**Issue by galmok** [sunjw/jstoolnpp#138]
I am trying to format this code using version 1.2205.0.0 x86 and it causes Notepad++ to crash:

{"responseHeader":{"status":0,"QTime":43,"params":{"q":"a:java-jwt","core":"","indent":"off","spellcheck":"true","fl":"id,g,a,latestVersion,p,ec,repositoryId,text,timestamp,versionCount","start":"","spellcheck.count":"5","sort":"score desc,timestamp desc,g asc,a asc","rows":"20","wt":"json","version":"2.2"}},"response":{"numFound":3,"start":0,"docs":[{"id":"com.auth0:java-jwt","g":"com.auth0","a":"java-jwt","latestVersion":"4.4.0","repositoryId":"central","p":"jar","timestamp":1680287596000,"versionCount":57,"text":["com.auth0","java-jwt","-sources.jar.sha256",".jar.asc.sha256","-javadoc.jar","-javadoc.jar.sha256",".jar.asc.sha512","-sources.jar.asc.sha512",".pom.sha512","-sources.jar","-javadoc.jar.sha512",".pom","-sources.jar.asc.sha256","-javadoc.jar.asc.sha256",".jar","-javadoc.jar.asc.sha512",".pom.asc.sha256",".jar.sha512",".pom.asc.sha512",".pom.sha256","-sources.jar.sha512",".jar.sha256"],"ec":["-sources.jar.sha256",".jar.asc.sha256","-javadoc.jar","-javadoc.jar.sha256",".jar.asc.sha512","-sources.jar.asc.sha512",".pom.sha512","-sources.jar","-javadoc.jar.sha512",".pom","-sources.jar.asc.sha256","-javadoc.jar.asc.sha256",".jar","-javadoc.jar.asc.sha512",".pom.asc.sha256",".jar.sha512",".pom.asc.sha512",".pom.sha256","-sources.jar.sha512",".jar.sha256"]},{"id":"com.github.robertomanfreda:java-jwt","g":"com.github.robertomanfreda","a":"java-jwt","latestVersion":"1.2.0-RELEASE","repositoryId":"central","p":"jar","timestamp":1587651625000,"versionCount":7,"text":["com.github.robertomanfreda","java-jwt","-javadoc.jar","-sources.jar",".jar",".pom"],"ec":["-javadoc.jar","-sources.jar",".jar",".pom"]},{"id":"de.notizwerk:java-jwt","g":"de.notizwerk","a":"java-jwt","latestVersion":"3.0.0","repositoryId":"central","p":"jar","timestamp":1473718949000,"versionCount":1,"text":["de.notizwerk","java-jwt","-javadoc.jar","-sources.jar",".jar",".pom"],"ec":["-javadoc.jar","-sources.jar",".jar",".pom"]}]},"spellcheck":{"suggestions":[]}}

Information from Windows Event Log:

Faulting application name: notepad++.exe, version: 8.4.8.0, time stamp: 0x63a7457f
Faulting module name: clr.dll, version: 4.8.4614.0, time stamp: 0x63995f05
Exception code: 0x80131506
Fault offset: 0x00307a76
Faulting process id: 0xb3a8
Faulting application start time: 0x01d976b061583846
Faulting application path: C:\Program Files (x86)\Notepad++\notepad++.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Report Id: e7fb6ab3-70b5-43c1-9333-39e51badb732
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 2211628987061628333, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: notepad++.exe
P2: 8.4.8.0
P3: 63a7457f
P4: clr.dll
P5: 4.8.4614.0
P6: 63995f05
P7: 80131506
P8: 00307a76
P9: 
P10:

**Comment by sunjw** [comment]
Not able to reproduce crash.
And from your log: "Faulting module name: clr.dll, version: 4.8.4614.0, time stamp: 0x63995f05" and "Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll", I think that crash is happening in "clr.dll", not in "JSTool".
