### ISSUE TITLE
Force edit on "read-only" file

### ISSUE THREAD

**Issue by sunjw** [sunjw/jstoolnpp#14]
Force edit on "read-only" file in option.

**Comment by NudeSpoons** [comment]
@sunjw 
Could you provide an update on your progress on providing this enhancement, please?

**Comment by aslze** [comment]
Not sure if this refers to the same issue. I came to this issues tracker to report this:

I just opened a JSON file directly from a web browser (you know click link, and "Open with...") into N++. I clicked "JSFormat" to read it easier (it was all in one compact line) and nothing happened. What? Clicked again and nothing. I later saw that the file had been opened as Read-Only so JSTool could not modify it. I had to save it somewhere else so it could be formatted.

So, a bit confusing. I guess when applying modification options (format, minimize...), the plugin should check if it is possible (or it's read-only), and do something like saving in a new temporary file.

**Comment by sunjw** [comment]
Won't fix
