### ISSUE TITLE
Bitdefender detection of JSMinNPP.dll

### ISSUE THREAD

**Issue by VektreX** [sunjw/jstoolnpp#147]
Earlier today as I opened Notepad++ I got an error message from Notepad++ about JSMinNPP.dll, and Bitdefender lit up and flagged the dll as Gen:Variant.Tedy.504791

I also checked out the downloads page from source forge and noticed that it was also blocked, with Bitdefender detecting the zip file as Trojan.GenericKD.70772555

Here's the Virustotal report for reference: https://www.virustotal.com/gui/file/c11d28501fb7301ffcc1ff6ffb5635c6ebe0cab6d0baedb763c82cfe2e76f9ea/detection

This is likely a false positive that you might have to work out with the antivirus vendors, although you may also want to check what you're building to see why it's being detected in the first place.

**Comment by donho** [comment]
@sunjw 
Could you check this issue with Bitdefender please?

**Comment by rdipardo** [comment]
It's most likely the usage of [internet-facing functions][0] that's getting flagged:

~~~sh-session
$ readpe --imports JSMinNPP.dll
Imported functions
# [ . . .]
    Library
        Name:                            WININET.dll
        Functions
            Function
                Hint:                            201
                Name:                            InternetOpenW
            Function
                Hint:                            149
                Name:                            InternetCloseHandle
            Function
                Hint:                            200
                Name:                            InternetOpenUrlW
            Function
                Hint:                            206
                Name:                            InternetReadFile
# [ . . .]
~~~

To give just one example of how dumb these heuristics really are: I usually shrink my plugin binaries with [UPX](https://upx.github.io) (a [red flag](https://github.com/upx/upx/issues/437) all by itself), yet the zipball still gets [a clean rating][1].

[0]: https://github.com/sunjw/jstoolnpp/blob/36154a3e682a3b2d9dfc9fafc09fd2c1d7086960/trunk/src/jsMinNpp.cpp#L736
[1]: https://www.virustotal.com/gui/url/0a6eeaabf1a6b0a41386fe3da42beb616fc2439fcd8fcc494628e9061446f4d4

**Comment by sunjw** [comment]
Just a clear false positive.
