### ISSUE TITLE
Keyboard Shortcuts Should be configurable.

### ISSUE THREAD

**Issue by SomeCallMeTom** [sunjw/jstoolnpp#150]
### #48 Ctrl + Alt + M has stopped working

I have come across a similar issue, where if the Keyboard Shortcuts conflict with other plugins I have installed, the shortcut is over-ruled. I suspect this is based on first-come-first-served based upon plugin loading, which I suspect is based upon folder name.

This could potentially be an issue for VSCode plug-ins.

**Comment by sunjw** [comment]
Yes, it is configurable. It is a feature of Notepad++ and the same feature in VSCode, too.
