### ISSUE TITLE
json viewer not visible?

### ISSUE THREAD

**Issue by codex1001** [sunjw/jstoolnpp#151]
When json is present, the json viewer window does not appear. I wanted to reset the plugin but there is no reset setting.
How can json viewer be made visible?
![cw573](https://github.com/sunjw/jstoolnpp/assets/135052551/b325ee28-4c09-4e65-86bc-c44f04eacf4c)

**Comment by sunjw** [comment]
Maybe you need to reset Notepad++. Plugin itself doesn't save window position and size, it is controlled by Notepad++.

**Comment by codex1001** [comment]
Hey, I found where the problem is. There is a bug in your plugin.
Settings->preferences->toolbar

When you change the standard icons (small) option here, all icons of your plugin disappear. However, there is no such problem in other json plugins. So the problem is related to your plugin.
![cw597](https://github.com/sunjw/jstoolnpp/assets/135052551/c3a03e63-0378-4cf7-9197-0ce5ffaeee22)

**Comment by sunjw** [comment]
I couldn't reproduce the problem you describe.
![Screenshot 2024-05-06 102053](https://github.com/sunjw/jstoolnpp/assets/846335/24dd6b01-6ec3-44f2-8c21-c045b1e52fc5)
