### ISSUE TITLE
Can I Get The Code To Format Json In C# Please?

### ISSUE THREAD

**Issue by SalmaBegumJSR** [sunjw/jstoolnpp#153]
Greetings,

first i must beg you to post a request, in a issue section, because i am very new to github, and i don't know where to ask for that kind of request.

now.. i really like the function that you did in that notepad++ plugin. which format the json code very nicely. I want to use that code/algorithm to format my json data in my program as well.

but the issue is, i am c# developer, and i do have zero knowledge on c++..

so, you or anyone? can give me the code in c# version? please? just the function that format/prettify the json string/text? please?

thanks in advance

best regards

**Comment by sunjw** [comment]
There must be some code formatters in NuGet. If you really want to use the code from this plugin, you can wrap the C++ code with C#.

**Comment by SalmaBegumJSR** [comment]
> There must be some code formatters in NuGet. If you really want to use the code from this plugin, you can wrap the C++ code with C#.

wow!
you responded sir? i am so amazed! **thanks a lot..**

i am sorry to say.. but i don't want to use another nuget library/reference just to format my json text, so, yes i like to use your plugin code. 

but again, as i have zero knowledge on c++, i really need your help to give me the code in c#? please? only the code to format the json string/text.

however, if you don't want or have enough time to write in c#, then you can just give me the function code in c++, i will try to convert them to c# using online resources..

thanks again

best regards

**Comment by SalmaBegumJSR** [comment]
@sunjw  as per your suggestion, i have do some nuget search and find a project as follows:
`https://www.nuget.org/packages/JsonFormatterPlus`

but this does not produce the formatted json as yours one does :(

this exactly product same format what is currently i able to do, please check the following link:
`https://stackoverflow.com/questions/78545563/c-sharp-json-pretty-print-format-better-than-what-chilkat-json-library-can-do`

thanks in advance for your upcoming help/support

best regards

**Comment by sunjw** [comment]
I don't think you need much knowledge of C++ to implement your idea. It's just call some function like C#.
You can refer to "sub-proj\JSFormatterTest\src\JSFormatterConsole.cpp", it is a very simple test code for formatter.

**Comment by SalmaBegumJSR** [comment]
@sunjw ,
dear sir, i even tried most of the solution from following link:

https://stackoverflow.com/questions/4580397/json-formatter-in-c

none of them are even close to yours :(

how did you find that logic? it's a GEM :)

best regards

**Comment by SalmaBegumJSR** [comment]
@sunjw 
if you don't mind do you know nay one who knows both c++ and c#? who could help me to do the conversion? please?

best regards

**Comment by sunjw** [comment]
Couldn't answer your last question.
