### ISSUE TITLE
Convert JS object to JSON

### ISSUE THREAD

**Issue by ygoe** [sunjw/jstoolnpp#154]
Today I needed to have a JSON file and was copying the data from a JS file. I didn't notice that the quotes around the property names were missing until my JSON parser said it can't handle that file. I was looking for such an option in this plugin but couldn't find one. So I had to find the nearest online tool for this task.

It would be great if this plugin could also convert between JS and JSON. This mostly means adding/removing quotes around property names. Removing of course only where possible.

**Comment by sunjw** [comment]
From JS to JSON, I think you can use the JSON sort function in this plugin.
From JSON to JS, JSON object is already a JS object (with strict code format rule), why bother to do this?
