### ISSUE TITLE
error when using jsmin on css

### ISSUE THREAD

**Issue by Joduai** [sunjw/jstoolnpp#156]
hi
I started using N++ again, and wanted to minify css. I remembered that jstool was doing this job perfectly.
After installation of the plugin I get an error when I try to use jsmin function on css, although jsformat functionality works as supposed. 
Jscript is being minified elegantly, without any problems.
Didn't change any option, everything is set to default.
Is there anything I can do to use jsmin function on css or this plugin is not supposed to support css anymore?

plugin ver: 1.2312.0.0 x64
npp ver: 8.6.9  x64

![jsminerror](https://github.com/user-attachments/assets/4587a2d6-0e1d-470b-a796-97ac74885bf2)

**Comment by sunjw** [comment]
Not support css.
