### ISSUE TITLE
Syntax with json5

### ISSUE THREAD

**Issue by qrqhuang** [sunjw/jstoolnpp#157]
I have some comment in the end of line . 
When use jstool to format it ,  the color too dazzling  and hardly to read it.
Can use json5 syntax as default?

## default with json view
![image](https://github.com/user-attachments/assets/1f99a434-2319-42b2-a31f-3fe9a0323f95)

## if with json5 view
![image](https://github.com/user-attachments/assets/6c28a59b-5872-4566-b176-42d8b58c9fb3)

**Comment by sunjw** [comment]
JSON and JSON5 are defined by notepad++. I think you should submit an issue to notepad++ project.

**Comment by qrqhuang** [comment]
@sunjw 那为什么Format之后，颜色会使用json的style。 你应该是驱动了什么样式配置吧

**Comment by sunjw** [comment]
Format 的时候识别出来是 JSON 而且你的文件目前没有设置格式，就会选择 JSON 格式。至于 JSON5 能支持 JSON 里面加上注释之类的，这个是 N++ 选择支持的，VSC 则支持 JSONC 格式。插件只负责到给你格式化和设置成 JSON，至于你希望 N++ 以何种形式支持 JSON 中有注释或者是某种松散的 JSON，这个是 N++ 的问题。这个插件并不判断你的 JSON 是该编辑器所支持的哪一种特定类型的 JSON。
