### ISSUE TITLE
Formatter breaks code that uses ES6  Arrow Functions

### ISSUE THREAD

**Issue by landofjoe** [sunjw/jstoolnpp#18]
Need support for ES6 arrow functions.  The current implementation breaks code, because it turns `=>` into `=  >`.

**Comment by sunjw** [comment]
Yes, working on that.

**Comment by sunjw** [comment]
Hi, @landofjoe 
If you are interested, you may try the latest source code.

**Comment by sunjw** [comment]
Support added from c4b183b15f8bad5b4b257cf433c9f907392de4d7.
