### ISSUE TITLE
it won't collapse json array

### ISSUE THREAD

**Issue by ironmanTony** [sunjw/jstoolnpp#19]
I don't find ways to open array ,cause the array is so long ,I want to make it more readable ,but is just in one line.

**Comment by sunjw** [comment]
Hi, @ironmanTony 
Cannot really understand what bug you described. Maybe you can use 中文.
And how JSToolNpp handle array depends on how original code is written, it only add some spaces into code.

**Comment by ironmanTony** [comment]
我使用他来格式化一个很复杂的json字符串，但是他不会给JsonArray换行，当然我这个jsonArray很长（length很大），其他的json格式化工具都会给JsonArray换行。     
比如"myArray" : ["data_1", "data_2", ....."data_1000"]，我想要的是：
"myArray" : [
"data_1",
"data_2",
...
"data_1000"
]

**Comment by sunjw** [comment]
所以，首先这个插件的目的是格式化代码，主要是为了给人写的代码格式化，也可以用来格式化机器自动生成的代码。第二，这个插件不会破坏原有的代码风格，如果写的人（或者是机器）不喜欢换行，使用了很紧凑的风格，那么格式化出来的代码也是紧凑的。
自然，这个数组很长（我猜是机器生成的，如果是人写的，会手工换行），但是读取的时候发现是紧凑的风格，那自然格式化过的代码也会遵循紧凑的风格。
最后，对于大部分的代码，数组换行很浪费空间，会让原来紧凑的函数变得很松散，反而不好看

**Comment by sunjw** [comment]
所以这个 issue 做为 won't fix，关掉了。还是很感谢反馈问题。
