### ISSUE TITLE
JavaScript formatting function freezes up Notepad++ UI

### ISSUE THREAD

**Issue by MayaPosch** [sunjw/jstoolnpp#22]
Running the latest Notepad++ with latest JSMinNPP.dll on Windows 7 x64 in VMWare VM on OSX:

Occasionally the JS formatting feature works, usually it just makes the Notepad++ UI freeze up (completely unresponsive) until the application is terminated from Task Manager.

The files being formatted are located in a shared folder on the filesystem of the OS X host.

**Comment by sunjw** [comment]
Yes, it is not multi-thread implementation. The formating process will freeze up UI. I recommand you put file in the VM to make the process faster. Is your file very large?
