### ISSUE TITLE
Formatting lambda wrong

### ISSUE THREAD

**Issue by Neur0mante** [sunjw/jstoolnpp#23]
When you call the formatter on a lambda expression 
`(var) => {}`
two spaces get inserted between the equal and the greater than sign, breaking the syntax.
`(var) =  > {}`
I suspect it gets recognized as an assignment.

**Comment by sunjw** [comment]
Hi @Neur0mante, very glad to tell you that in the latest release (1.18.0), this bug has already been fixed. You may like to download version 1.18.0 from https://sourceforge.net/projects/jsminnpp/ and try to format lambda with it. Thanks.

**Comment by Neur0mante** [comment]
Thank you very much. I see you also fixed the `${var}` formatting issue which I was about to post. Nice work.
