### ISSUE TITLE
New line before '{' causes error for return object

### ISSUE THREAD

**Issue by underr-ua** [sunjw/jstoolnpp#24]
If use _New line before '{'_ for something like this:
`return { a: 0, b: 1 };`
it changes to

```
return
{
    a: 0,
    b: 1
};
```

and causes an error.

**Comment by sunjw** [comment]
Thanks for reporting this bug.
I'll see if it can be fixed soon.

**Comment by NudeSpoons** [comment]
@sunjw How soon?

**Comment by sunjw** [comment]
Remove "new line before '{'" support.
