### ISSUE TITLE
[Feature Request] Extended option for added new line and added spaces

### ISSUE THREAD

**Issue by underr-ua** [sunjw/jstoolnpp#25]
Can we get an option to no added new line after '}' in case of '})' ?

Ex:

```
(function (data)
{
...
})

```

Can we get an option to no added new line after _if_ or _for_  when used only one operation?

Ex:

`if ( a > b ) return;`

It would be really nice to have something for adding spaces into the conditions brackets .

Ex:

```
if ( a > b ) 
{
...
}

for ( var i = 0; i < 10; i++ ) 
{
...
}
```

**Comment by sunjw** [comment]
Really thanks again.
Let's see what can be done to make this plugin better.

**Comment by NudeSpoons** [comment]
@sunjw 
Your last comment was 142 weeks ago - that's almost 3 years!
Do you still intend to make this plugin better? Or have you abandoned it?

**Comment by sunjw** [comment]
Hi, @NudeSpoons 
I just don't know why you comment on almost all issues here. And I do find that my last code commit is just one month ago. If you do care about some open source project, please post some meanful comments or create a pull request to fix some issue, thanks.

**Comment by sunjw** [comment]
Remove "new line before '{'" support.
