### ISSUE TITLE
no semicolon variable declaration with assignment

### ISSUE THREAD

**Issue by Neur0mante** [sunjw/jstoolnpp#26]
I noticed that if you dont use semiclons a new indent gets added after a variable declaration with assignment, but only for the first declaration in a block. I don't even know if you support no semicolon sintax but since it almost works it would be nice to have it.

```
if (index = 0) {
    var a
    var test = 4
        test = index + test
        var test1 = 0
        test1 = test - index
        if (a < b) {
            console.log(c)
            var target,
            test1 = 7
                c++
                var d = 1
                target = a - b
        }
}

```

(dont mind the code it's total gibberish for indent testing purposes)

**Comment by sunjw** [comment]
No, this plugin is not really support no semicolon syntax.

**Comment by Neur0mante** [comment]
Ok thanks. In case you'd ever want to try implementing it there's also an indenting issue with one line if.  For not supporting it it's already doing a pretty good job anyway. A lot of node.js codes are written without semicolons so it would be useful to have.

**Comment by sunjw** [comment]
I reopen this for issue reminding.

**Comment by NudeSpoons** [comment]
@sunjw 
Could you provide an update on your progress with this bug, please?
