### ISSUE TITLE
Issue with Notepad++ v7 64 bit

### ISSUE THREAD

**Issue by rgrajan** [sunjw/jstoolnpp#30]
I am using Notepad++ v7 64 bit 21-Sep-2016 build, it shows compatibility error while opening the notepad. Is this because of 64 bit version? I have attached the screenshot of the error.

![image](https://cloud.githubusercontent.com/assets/7380733/18820985/1f47b15c-8370-11e6-999c-664c005c0b1c.png)

**Comment by sunjw** [comment]
Yes, it is because 64bit. I'll work on 64bit support soon and maybe a 64bit beta version in few days, thanks for report this issue.

**Comment by sunjw** [comment]
Support 64bit npp from dda55d628c3fe1c0a89a18b1d7402ec767477193.
