### ISSUE TITLE
JSFormat messes Bookmarks

### ISSUE THREAD

**Issue by uclaros** [sunjw/jstoolnpp#31]
When using JSFormat on a selection that contains a npp bookmark, the bookmark is moved to the last selected line.
When using JSFormat without any selected text, the bookmarks are removed.

I believe the desired function would be to preserve the bookmarks at their original line, even if the line is split during the formatting.

**Comment by sunjw** [comment]
@uclaros I don't think this is a bug of JSToolNpp plugin. I've tried other plugins who can edit a block of text with bookmark, the bookmark also been moved or removed. It seems that npp's bookmark doesn't handle text change well.
