### ISSUE TITLE
Disable "Phoning Home" - Plugin trying to access internet

### ISSUE THREAD

**Issue by openSoftMan** [sunjw/jstoolnpp#33]
After installing this plugin, my NotePad++ attempts to access the internet.  Can you add an option to disable this behavior?

**Comment by sunjw** [comment]
No, I've no plan to add an option to disable internet connection currently. It is update check and only read "https://raw.githubusercontent.com/sunjw/jstoolnpp/master/trunk/ReleasedFiles/ReleaseVersion.json" to see if there is a newer version. It won't download file to your system, and also won't change files on your system. If JSToolNpp need do more with internete access, I'll consider to add an option for user to disable it.
