### ISSUE TITLE
Suggestion: improved handling/preview of newline in strings

### ISSUE THREAD

**Issue by albinsunnanbo** [sunjw/jstoolnpp#41]
Hi
I have a suggestion for improvement in the JSON Viewer
If I have strings with encoded newlines \r\n as in the image below
![image](https://cloud.githubusercontent.com/assets/5158396/22583197/5f740104-e9eb-11e6-8d68-dde33297e6e9.png)
it is cumbersome to read the content.
Would it be possible to have a "preview" or something on string values that opens a decoded version of the string in a multi line textbox?
That way you would be able to read strings better and copy'n paste the content to another document.

**Comment by sunjw** [comment]
Good suggestion! Thanks.
