### ISSUE TITLE
[Feature Request] Make update check at startup optional

### ISSUE THREAD

**Issue by Big--Mike** [sunjw/jstoolnpp#44]
Hi,

could you please make the update check at startup optional or remove it completely?

Every time Notepad++ is started, it tries to connect to the internet. We identified JSTool as reason and therefore removed this plugin from our distribution package.
In our company, we have a strict policy regarding used software. Employees are not allowed to install any software (or even newer versions) on their own and all software needs to be tested and distributed by our IT department. Therefore, we disable all auto update functions to minimize support requests.

Maybe this feature is a useful thing for home users, but as Notepad++ has its own plugin manager, it also shouldn't be needed for home users.

We'd really be pleased to add JSTool again to our package.

**Comment by sunjw** [comment]
Hi, really glad to know your company uses this plugin.
If I add a non-GUI option (or GUI option) for auto update checking, but make it on as default, will this meet requirement of your company policy? Or it must be default off?

Npp has its own plugin manager, but its data update really slowly. Sometimes behind half a year. So I added this auto-update checking.

**Comment by Big--Mike** [comment]
Hi, thank you. Adding an option to disable it, will suffice. We build our own installation packages and therefore can disable it with our own default settings. I guess it will be a simple option in the ini file?

**Comment by sunjw** [comment]
OK, I'll implement this soon.

**Comment by Big--Mike** [comment]
Thank you

**Comment by sunjw** [comment]
Add GUI option at f2755e649a7d762fcf7cd30c5d68581a7f30a1bf

**Comment by Big--Mike** [comment]
Hi, would it be possible to release a build, that we can use?

Thank you :)

**Comment by sunjw** [comment]
@Big--Mike I can give you a build based on current code, but it won't be released in Plugin Manager. Is that OK? I'm working on some other features. You can still get update when I released in Plugin Manager

**Comment by sunjw** [comment]
@Big--Mike Your build:
https://www.ssfe.trendmicro.com.cn/app#folder/KPxGh/JSToolNpp/JSMinNPP.dll?a=b8kJHdIy_2w

**Comment by Big--Mike** [comment]
Hi, thank you. We will test and deploy it on our clients.
Good luck for the new features.
