### ISSUE TITLE
Can not save options

### ISSUE THREAD

**Issue by antonbabkin** [sunjw/jstoolnpp#46]
Clean download of Notepad++ minimalist package 32-bit x86, v7.3.3
Download JSMinNPP.dll - Unicode 32bit build - JSToolNPP.1.20.2.uni.32.zip
Put in plugins folder.

Plugin appears and works, but options are not saved when clicking "OK". So it only works with default options.

**Comment by sunjw** [comment]
Hi @antonbabkin 
Which path do you put your npp in? Do npp has the permission to write the folder? Does other plugin able to save option?

**Comment by sunjw** [comment]
Hi @antonbabkin 
I just install a npp 32bit 7.3.3 on Windows 7 and install my plugin from plugin manager, and found it is able to save options.
Do you install npp from installer or just unzip from a zip package?
If you install it from installer, do you allow npp to use %APP_DATA%?

**Comment by antonbabkin** [comment]
Hi @sunjw 
Thanks for your quick response.

In put npp in a folder on Desktop, where I should have all permissions. I do not use plugin manager, I manually download and put plugin .DLL into "plugins" subfolder. This is Windows 10 running on a Mac computer.

I tried same setup (minimalist NPP) with a different plugin, NppExec. It is a little different. With JSToolNPP, if I change options, click Ok button, and open options again, all changes are gone. With NppExec, if I change options, click Ok, and open options again, changes remain. But after I restart NPP, changes disappear.

Lastly, I tried to do the same with a full NPP package:
Notepad++ zip package 32-bit x86: Don't want to use installer? Check this one (zip format) (v7.3.3)
And it works just fine! Again, I manually added JSToolNPP and NppExec DLLs to the "plugins" subfolder, and I am able to change and save options on them.

It must be something about the difference between standard and minimalist NPP package. Do you have any ideas?

**Comment by sunjw** [comment]
Hi @antonbabkin 
Sorry, no idea about the difference between standard and minimalist NPP package. You may ask NPP's developer. This looks like a permission problem.

**Comment by antonbabkin** [comment]
Follow up Npp issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3238
