### ISSUE TITLE
Not able to comment code

### ISSUE THREAD

**Issue by diller0708** [sunjw/jstoolnpp#47]
After using jstool to format a javascript file, it disables the ability to comment code from shortcuts. Every time I apply the format, I have to reopen the file to be able to comment code. The commenting function is working on other languages. 

Notepad++ 7.5.1
JSTool 1.21

**Comment by sunjw** [comment]
@diller0708 What "comment code from shortcuts" feature you use? I really don't know where is this feature in npp.

**Comment by sunjw** [comment]
@diller0708 It seems not a bug of this plugin. It's a bug of npp. After you open any js file, click menu
> Language => J => JavaScript
You will find comment function not work anymore.
This plugin will set file language to JavaScript just like you click the menu item.

**Comment by sunjw** [comment]
@diller0708 Is your npp 7.5.1 different from clean installed npp 7.5.1.
I can reproduce this issue on my really old npp 7.3.1, but cannot reproduce on a clean installed npp 7.5.1.

**Comment by diller0708** [comment]
@sunjw Yes that was the problem. It must of kept some settings when I updated. Did a clean install and everything working. Thanks
