### ISSUE TITLE
Can json viewer check the file change ,auto refresh?

### ISSUE THREAD

**Issue by ricardo0624** [sunjw/jstoolnpp#49]
Json viewer is really convenient and useful,but it need to refresh by clicked ,Is it possible to refresh automatically?

**Comment by sunjw** [comment]
Good idea, but may not be implemented soon.

**Comment by ricardo0624** [comment]
@sunjw As I know ,like vs code ,it's js tool doesn't have json viewer function,so Json viewer is really convenient .Thanks you!
Can json viewer support more function like webStorm?
but webstorm's structure ,array don't show index.
like expand all(one click,expand a step ),collapse all(collapse all just one click)?
If this , this will be prefect ,and sometimes people use notepad++ for having js tool(such a good js tool)

**Comment by sunjw** [comment]
@ricardo0624 As I know, you are Chinese? 我直接写中文了，expand/collapse all 在右键菜单里面有。其他功能会酌情增加，毕竟是个业余项目。有考虑移植到 vscode，正在探索可能性。

**Comment by ricardo0624** [comment]
@sunjw 好吧,我没仔细看,原来你再南京.没想到这么优秀,而且是国人做的,厉害.
expand/collapse all 的确有,我没仔细看,作者又是比较忙,可以理解,本来就是无私奉献.
谢谢了

**Comment by sunjw** [comment]
感谢使用这个软件，感谢提建议。
