### ISSUE TITLE
Sort Alphabetically for JSON

### ISSUE THREAD

**Issue by daharmon** [sunjw/jstoolnpp#50]
May I suggest having an option to sort the json objects alphabetically? For large json files with many fields, it is always helpful for viewing when they are ordered. Great work on this plugin!

**Comment by sunjw** [comment]
You sure? Repect JSON order is an important feature. If you know what you are looking for, you can use search, I think.

**Comment by daharmon** [comment]
I have a project that calls a third party REST service. There are about 1000 fields in it and they are randomly sorted which makes it difficult to browse. I use this site [http://novicelab.org/jsonabc/] to then sort so I can find certain things. Search doesn't always work because I may not know exactly what I'm looking for.

**Comment by sunjw** [comment]
I just let this issue open. And to see if it is an useful feature.
Thanks for reporting this and using this plugin.

**Comment by Peter-Optiway** [comment]
This would be awesome.
In my job i compare a lot of json files but that is quite difficult when the order of fields changes..
If they where sorted this issue would go away for me!

**Comment by taxi16** [comment]
The functionality would be great, for the same use case as Peter has, comparing json's. latest then the same order is really important (@sunjw: we had the issue on Mo 15.01.2018 03:18 CET, if you find the time that would be awesome)

**Comment by sunjw** [comment]
@taxi16 Got. Thanks

**Comment by sunjw** [comment]
Hi, all, @daharmon @Peter-Optiway @taxi16 @NN--- 
Version 1.21.10.0, implemented "JSON Sort" function for testing.
x86: https://www.dropbox.com/s/w9vortmivf31g6v/JSMinNPP.dll?dl=0
x64: https://www.dropbox.com/s/jb8iihzgxtegtp1/JSMinNPP64.dll?dl=0
Would you like to try these build, and tell me if it satisfied your request, thanks.

**Comment by Peter-Optiway** [comment]
Tested it on a small json file and it worked like a charm!

**Comment by sunjw** [comment]
Add this feature after 6658750b57b7da3d1979a7b7567ddc3b7ebb1582.
