### ISSUE TITLE
Validation of json content

### ISSUE THREAD

**Issue by SanTech7182** [sunjw/jstoolnpp#51]
Is it possible to add a validation menu option for the plugin. On clicking on the validation it should show whether the content is the text document is a valid json or not. 

For ex., for below Json:
{
"test": "123"
}

the validation result should be "Valid Json"

For below Json:
{
"test": "124
}

the validation result should be "Invalid Json, at line 2 (missing quote)"

**Comment by donho** [comment]
+1

**Comment by geminorum** [comment]
also escaping unicode strings.
