### ISSUE TITLE
增加编译好的dll

### ISSUE THREAD

**Issue by sonichy** [sunjw/jstoolnpp#52]
sourceforge有时候打不开，比github还要糟糕。

**Comment by sunjw** [comment]
@sonichy 你可以自己编译，vs08 v15 均能直接编译通过。如果你能上 github 我相信你也能上 sourforge，通过 npp plugin manager 装起来是有点困难，可以直接从这里下载。

**Comment by sonichy** [comment]
找了一下，在trunk目录里，为什么取这个名字？

**Comment by sunjw** [comment]
@sonichy 因为是 svn 转过来的。没啥问题就 case closed。
