### ISSUE TITLE
wrong indentation when formatting a large js file

### ISSUE THREAD

**Issue by hundan2020** [sunjw/jstoolnpp#53]
when I trying to formatting the js file, I got some wrong indentation.Just like the screenshots.As you can see, there are lots of space in the end line.
I think it's a bug, by using [this online tool](http://tool.oschina.net/codeformat/js/), I got different result.
And it's the js file.
[videoComponent.zip](https://github.com/sunjw/jstoolnpp/files/1490106/videoComponent.zip)

![20171121130349](https://user-images.githubusercontent.com/9510938/33055813-e1cd971c-cebc-11e7-9006-c3a699af5ee0.jpg)
![20171121130734](https://user-images.githubusercontent.com/9510938/33055881-38ffd22a-cebd-11e7-845c-68c0684caee3.jpg)

**Comment by hundan2020** [comment]
JSToolNpp version:1.21.1.0 x64
notepad++ version:7.3.2 x64
operating system: windows 10 x64

**Comment by sunjw** [comment]
@hundan2020 This bug has been fixed in the latest code but not released yet. Maybe you want to try this dev build:
32bit: https://www.dropbox.com/s/w9vortmivf31g6v/JSMinNPP.dll?dl=0
64bit: https://www.dropbox.com/s/jb8iihzgxtegtp1/JSMinNPP64.dll?dl=0
