### ISSUE TITLE
Options for JSMin (New file)

### ISSUE THREAD

**Issue by paul-git** [sunjw/jstoolnpp#54]
Hey there,
it would be great to have some options for the **JSMin (New file)** Script: I would love to automatically have it saved with the same name, but with *.min* attached. E. g. *script.js* becomes *script.min.js*. 

I don´t know how hard it is, if even possible, but if you could save the file directly, it would save some time :) So I would say it´s like "Export minifed". Then instead of leaving it open, you could just save the file in the background.

The necessary options would be:
* Which suffix? With default *.min*
* Which folder? With default *same folder* (I don´t know how manageable it is to save different folders for different files. So maybe not offered as an option, but have it fix in the same folder).
* Overwrite when existing? With default "prompt" (other options would be *yes* or *always* and *no* or *never*).

Thanks for this great plugin, 
Paul

**Comment by sunjw** [comment]
Hi, @paul-git 
I think if you need this kind of feature, there are lots of other professional tool to minify (compile) you scripts and export to some destination. JSMin in JSToolNpp is not, I "think", a professional tool to do this and also not as good (easy to use, industry level minify/compile result) as other tools.

**Comment by paul-git** [comment]
Hey @sunjw,

I actually think your tool is pretty good! Don´t hide your light under a bushel.

I understand what you say, nevertheless I think your tool is by far the most comfortable available on the market. All the other tools need commandlines and parameters and have complicated concepts to be more powerful: overkill!

But I can totally live with pressing CTRL + S and click on the minified file myself to replace it ;)

Thanks again for this great tool,
Paul
