### ISSUE TITLE
Incorrect format for split

### ISSUE THREAD

**Issue by DMENNERET** [sunjw/jstoolnpp#56]
Before JSFormat
var tabDateDebutPeriode = (dateDebutPeriode.split(/[- //]/));

After JSFormat
var tabDateDebutPeriode = (dateDebutPeriode.split(/[- //] / ));

This last instruction is incorrect and produce an incorrect date.

**Comment by sunjw** [comment]
Hi, @DMENNERET 
I'd like to know what your mean of "//" in "/[- //]/". If you want to match a '/', maybe you need to use '\/' to escape '/'. If you want to match '//', maybe you need to use '\/\/'.
I admit this is a bug that the parser in JSFormat is not able quite understand your regex. But I think '\/' will be more "correct" in js.
So maybe:
var tabDateDebutPeriode = (dateDebutPeriode.split(/[- \/\/]/));
is better, I think.

**Comment by DMENNERET** [comment]
Hi Sun,
I want to split dates that are written 10-10-2018 or 10/10/2018, so only one /.
Regards

**Comment by sunjw** [comment]
So then:
var tabDateDebutPeriode = (dateDebutPeriode.split(/[- \\/]/));

**Comment by DMENNERET** [comment]
This syntax is correct and produce the expected result in Javascript. Moreover, in this case, no issue with JSTool.
Thanks.
