### ISSUE TITLE
Very slow startup on notepad++ in last version.

### ISSUE THREAD

**Issue by digovc** [sunjw/jstoolnpp#58]
Hi,

With the JSMinNPP enabled the notepad++ is so slow in startup (5~7 seconds). When I rename the JSMinNPP.dll to JSMinNPP.dll.old it opens instantly.

Some hard task put in the startup event?

**Comment by sunjw** [comment]
Hi, @digovc 
There is an issue #57 seems to be the same issue to this issue.
Here is a test build link in my comment, would you like to try it.
https://github.com/sunjw/jstoolnpp/issues/57#issuecomment-377435473
Thanks very much.

**Comment by digovc** [comment]
This version works like a charm, thanks! 

1s or less to open notepad++

**Comment by sunjw** [comment]
Duplicated to #57
