### ISSUE TITLE
feature request:   un-minify a JavaScript file

### ISSUE THREAD

**Issue by WiliTest** [sunjw/jstoolnpp#59]
Thanks a lot for your work! 

It would be great to un-minify js files (maybe using [js-beautify ](https://github.com/beautify-web/js-beautify) (not sure if that's possible though!) ).

**Comment by sunjw** [comment]
Hi @WiliTest , JSFormat doesn't satisfy you?

**Comment by WiliTest** [comment]
Oh sorry! Yes that's it! Thanks a lot for your answer!
