### ISSUE TITLE
JS Format regex issue

### ISSUE THREAD

**Issue by AlexanderMisel** [sunjw/jstoolnpp#60]
```js
con = con.replace(/(?:(?:https?|ftp):\/\/|www\.|\\\\)[^\s/$.?#].[^\s]*/g, `<a class="link" href="javascript:clickLink('$&')">$&</a>`);
```
js format output
```js
con = con.replace(/(?:(?:https?|ftp):\/\/|www\.|\\\\)[^\s/$. ?  # ].[ ^  \ s] *  / g, `<a class="link" href="javascript:clickLink('$&')">$&</a>`);
```
The regular expression shouldn't be modified.

**Comment by AlexanderMisel** [comment]
似乎是因为`[^\s/$.?#]`里面的`/`没有转义的缘故。不过在`[]`里可以不用转义的吧？看你的formatter文档好像这儿直接作为正则结尾处理了。

**Comment by sunjw** [comment]
需要转义，参考 #56 
我看一下是不是可以考虑支持在 [] 中不转义

**Comment by sunjw** [comment]
@AlexanderMisel Would you like to try test build:
https://www.dropbox.com/s/w9vortmivf31g6v/JSMinNPP.dll?dl=0

**Comment by AlexanderMisel** [comment]
Thanks. I'll have a try.

**Comment by sunjw** [comment]
@AlexanderMisel Here it is
https://www.dropbox.com/s/jb8iihzgxtegtp1/JSMinNPP64.dll?dl=0

**Comment by AlexanderMisel** [comment]
Thanks. It works.

**Comment by sunjw** [comment]
OK, case close.
