### ISSUE TITLE
JSON Sort removing double quotes

### ISSUE THREAD

**Issue by Shwaffle** [sunjw/jstoolnpp#65]
When using the JSON Sort option, it is altering code in an undesirable way.

A section of code [here](https://gist.github.com/Shwaffle/f254a9f4e8546e8b7655094429a9fb9a) at Line 8 shows:

    "height": "6'3\"",

However, after doing JSON Sort, the code turns into [this](https://gist.github.com/Shwaffle/79d5fa413ecf4a6748cb4d4ec2ac85e9). As you can see, it's removing the double quotes and invalidating the JSON file. It would be nice to either have this not happen anymore, or an option to stop this.

**Comment by sunjw** [comment]
Fixed in df8d998e14eab92882db9e81f79b48e2137628ab
I'll release new stable version soon.
If you like to try debug build, please download here:
https://www.dropbox.com/s/w9vortmivf31g6v/JSMinNPP.dll?dl=0
https://www.dropbox.com/s/jb8iihzgxtegtp1/JSMinNPP64.dll?dl=0
