### ISSUE TITLE
JSTool's options cannot be saved when notepad++ installed in a dir which has blank (space) in full path

### ISSUE THREAD

**Issue by AnyinSong** [sunjw/jstoolnpp#66]
### Description of the Issue

JSTool's options cannot be saved when notepad++ installed  in a dir which has blank in full path
### Steps to Reproduce the Issue

0. Install  notepad++ in "C:\Program Files (x86)\Notepad++"
1. Put JSMinNPP.dll (ver 1.22.0) into plugins directory
2. Restart notepad++
3.  Modify any option in plugins->JSTool->Options and click OK
4.  Check the option  in plugins->JSTool->Options

### Expected Behavior

options  changed should be saved
### Actual Behavior

all options are still default value  even though I have modified  them in step 3.

**Comment by sunjw** [comment]
Hi, @AnyinSong 
I cannot reproduce the bug you reported.
I've installed Notepad++ 7.5.6 x86 on a Windows 10 x64 machine, within the path "C:\Program Files (x86)\Notepad++" as you described and which is also the default path in installer. Copy JSMinNpp.dll into plugins dir under "C:\Program Files (x86)\Notepad++". I've tried change options and everything works well.
I'd like to know if you changed these options when installing npp.
![npp installer](https://user-images.githubusercontent.com/846335/46254247-ba1b9400-c4be-11e8-8ba6-88a9ca61a162.png)
If you checked 1st option, npp will save plugin option files into install directory which is "C:\Program Files (x86)\Notepad++". But the "Program Files" directory is protected by Windows, and npp with normal privilege cannot modify files under this path.
If you installed npp with all default option (click Next without change anything), npp will save plugin option files under "C:\Users\$your_user_name\AppData\Roaming\Notepad++\plugins\config\" which is able to modify by normal privilege process.
So I think you need to check if you have changed this option when you install npp, and if the config directory is under your account path.
Thanks.

**Comment by AnyinSong** [comment]
@sunjw ，I checked “Don't use %APPDATA% ” and installed 7.5.8 x86 on win7 x64 and win10 x64.  I have changed install dir to "C:\Program_Files\Notepad++" to avoid this problem ^_^
