### ISSUE TITLE
Don't format outside of script tags

### ISSUE THREAD

**Issue by AyrA** [sunjw/jstoolnpp#67]
Pressing CTRL+ALT+M to format the code is really useful and I use it a lot.
The problem is that JS code is often bundled inside of HTML code. If you use the hotkey without marking the JS lines, the entire document is messed up because it formats the HTML tags too.

Please allow us to configure file extensions where the formatter will operate in a "script tags only" mode.

Default should probably be something like `/.(html?|xml|php|asp|aspx)$/i`

As an alternative, a whitelist would be `/.js(on)?/i`

**Comment by AyrA** [comment]
> JSTool supports format selected code

That's literally what I mentioned in the issue. The problem is that it's easy to forget and it destroys the entire HTML document

**Comment by sunjw** [comment]
I'll leave this issue open, and to see if others like this feature.
