### ISSUE TITLE
Format shortcut not working

### ISSUE THREAD

**Issue by WrongWay** [sunjw/jstoolnpp#69]
Pressing `Ctrl+Alt+M` does nothing, with or without anything selected. Saving the file or setting the language type doesn't help.

Debug info:
```
Notepad++ v7.6   (64-bit)
Build time : Nov 13 2018 - 00:12:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll 
```

**Comment by sunjw** [comment]
Hi, @WrongWay 
I cannot reproduce this issue. Which version of JSToolNpp you are using? Is your file read-only? Can you see JSTool in Plugins menu?

**Comment by sunjw** [comment]
Looks like duplicated to https://github.com/sunjw/jstoolnpp/issues/48
