### ISSUE TITLE
[Feature Request] Need options to delete,copy a node in Json Viewer Tree

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sunjw/jstoolnpp#7]
```
The following are the feature requests i want in this ?
1. Right Click on Node in Treeview in Menu -> Copy Node  (copy node with value )
2. Right Click on Node in Treeview in Menu -> Copy Node Value ( copy just value 
of the given node )
3. Right Click on Node in Treeview in Menu -> Delete Node ( Deletes the current 
node ).
4. Right Click on Node in Treeview in Menu -> Expand All / Collapse All of node 


What version of the product are you using? On what operating system?
 1.16.0.0 , Notepad ++ (5.9.6.2 Unicode ) , Win 7 32 bit

Please provide any additional information below.

You can say that click on node and copy/ delete in the text view only but if 
node is big then its little difficult to copy node / delete . It will be very 
helpful , if this feature is done.


```

Original issue reported on code.google.com by `gopikris...@gmail.com` on 24 Nov 2013 at 7:35

**Comment by sunjw** [comment]
Implement 
1. Right Click on Node in Treeview in Menu -> Copy Node  (copy node with value )
2. Right Click on Node in Treeview in Menu -> Copy Node Value ( copy just value 
of the given node )
4. Right Click on Node in Treeview in Menu -> Expand All / Collapse All of node 
after c5a3835c23362366059d651860991d8dc1e5d49d

**Comment by sunjw** [comment]
This is a JSON viewer and will not provide editing features now, so not to implement "Delete node".
Other features in this issue are implemented, so close it.
