### ISSUE TITLE
[Feature Request] JSON Language option for JSFormat

### ISSUE THREAD

**Issue by Klober81** [sunjw/jstoolnpp#72]
JSFormat does a wonderful job of formatting not just JS but JSON as well - which is my main use for it. However, needing to change the Language from JavaScript to JSON each time I use JSFormat is driving me crazy! Yes, I realize it's a small price to pay for the ease with which I can format JSONs but if you could find it in your heart to add a simple option in the JSTool Options panel to choose between JS and JSON for the language set when JSFormat is run this would truly be the perfect JS tool in my eyes!

**Comment by sunjw** [comment]
Try to guess JSON content and set language right.
1211d39f0e68337d1acd2a63785a5494e36cf5c8
