### ISSUE TITLE
Help to understand, there is no build of the project for 64bit

### ISSUE THREAD

**Issue by andrecool-68** [sunjw/jstoolnpp#73]
The virtual machine has Visual Studio 2008 installed, windows 7 64 bit and windows 7 32 bit
When I start compiling a plugin for 32 bit, the build is successful. But when I start building a project for 64 bit, nothing happens at all.

**Comment by sunjw** [comment]
Cannot understand what you report. The VS project file within this repo including 32 and 64 bit configuration.

**Comment by andrecool-68** [comment]
![1](https://user-images.githubusercontent.com/3471892/54811263-f91deb80-4c90-11e9-8d3b-19e81185327c.png)
![2](https://user-images.githubusercontent.com/3471892/54811266-f9b68200-4c90-11e9-8a47-85c66fe0a57c.png)
@sunjw 
I do not know why, but the 64-bit build does not work for me

**Comment by andrecool-68** [comment]
Watch this video. What am I doing wrong, why can't I build 64 bit?

![Запись_2019_03_22_18_07_40_337](https://user-images.githubusercontent.com/3471892/54836854-bdeddd80-4ccd-11e9-80f1-e31ee93c40fb.gif)

![Запись_2019_03_22_18_09_17_690](https://user-images.githubusercontent.com/3471892/54836855-be867400-4ccd-11e9-8584-e7cd34e63592.gif)

**Comment by andrecool-68** [comment]
@sunjw 
> The VS project file within this repo including 32 and 64 bit configuration.

I can't compile a 64-bit project. Please help to find the cause of failure.

**Comment by andrecool-68** [comment]
@sunjw 
Found the cause of the error!  
Visual Studio 2008 did not install the x64 compiler by default!
The question can be closed)))

**Comment by sunjw** [comment]
OK, thanks.

**Comment by andrecool-68** [comment]
Add the system requirements for building the project to the Help to avoid such issues)
