### ISSUE TITLE
Format not working correctly for large JSON files

### ISSUE THREAD

**Issue by roblangston** [sunjw/jstoolnpp#74]
When trying to format large JSON files, the formatted output generated through JSTool->JSFormat is not valid JSON.  It seems to be a problem when the JSON value contains a space (see examples below).

![json](https://user-images.githubusercontent.com/13354992/56359767-6a8e8280-61da-11e9-8a74-69ad9ddf3a1e.png)

**Comment by sunjw** [comment]
```
{
    "Date": "2019-04-11",
    "Code": "Last
    Code",
}
```
The JSON in input is something like above?
Is there a new line in JSON value?
Or does JSTool make a new line in JSON value to make it invalid JSON?

**Comment by roblangston** [comment]
Yes, JSTool seems to make a new line in the JSON when the JSON value contains a space character.  The JSON was very long ~ 10,000 lines and it seemed to be a problem at the line wrapping boundary.

**Comment by sunjw** [comment]
@roblangston Could you send me the JSON file?
