### ISSUE TITLE
Plugin package hash missmachted

### ISSUE THREAD

**Issue by pschneider87** [sunjw/jstoolnpp#76]
I want to install JSTool from the PluginManager in Notepad++, but constantly getting an hash-error

![image](https://user-images.githubusercontent.com/17707309/62514591-f70f9000-b81f-11e9-9093-95d69a0c6d28.png)

Also directly placing the "JSMinNPP.dll" into the plugin folder won't bring me the JSTool in N++

Any ideas?

**Comment by sunjw** [comment]
Npp has its own "Plugins Admin", JSTool has been moved to it now. This 1.1905.1 in "Plugin Manager" is not submitted by me, I'll check.

**Comment by sunjw** [comment]
@chcg

**Comment by chcg** [comment]
@sunjw The output above is not from PluginManager which still uses md5 checksums (https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/validate.json#L97), but from N++ builtin PluginAdmin (sha256 hash, see https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x64.json#L270).

**Comment by sunjw** [comment]
Hi @chcg 
Thanks very much. And '338cf91653094746452f344ed0e25dc11fe48bf1de3fe4fb41e20a44927f905b' is the correct checksum.

**Comment by pschneider87** [comment]
@chcg sure, here you go:

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll XMLTools.dll

**Comment by psined1** [comment]
Hi, any update on this one? MD5 still looks broken, both for Notepad++ v7.8 in x86 and x64

**Comment by chcg** [comment]
Hi,

I can't reproduce it with builtin PluginAdmin of N++:

```
Notepad++ v7.8   (64-bit)
Build time : Oct  4 2019 - 00:19:37
Path : C:\Users\chcg\npp.7.8.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.418
Plugins : BigFiles.dll DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll 
```

To add the dll manually since 7.6.x it need to be placed under

```
...\Notepad++\plugins\JSMinNPP\JSMinNPP.dll
```

**Comment by chcg** [comment]
@sunjw Could you please check the ssl certificate of https://www.sunjw.us/ seems it expired on 13.8.2019.

**Comment by sunjw** [comment]
> 
> 
> @sunjw Could you please check the ssl certificate of https://www.sunjw.us/ seems it expired on 13.8.2019.

Hi @chcg my web host doesn't support HTTPS and I don't even know why they open 443 port.
Also, I tested to accept the certificate, then it shown an 404 page.

**Comment by sunjw** [comment]
> 
> 
> > @sunjw Could you please check the ssl certificate of https://www.sunjw.us/ seems it expired on 13.8.2019.
> 
> Hi @chcg my web host doesn't support HTTPS and I don't even know why they open 443 port.
> Also, I tested to accept the certificate, then it shown an 404 page.

Oh... I found that my web hoster (aliyun) supports HTTPS for my product now, I'll enable HTTPS access soon. But currently, HTTPS://www.sunjw.us is not HTTPS of my site.
The plugin is download from sf.net with HTTPS, I cannot see why the checksum is not right. I can only guess that file is partially downloaded.
Counld @psined1 @pschneider87 do a check with my fHash https://github.com/sunjw/fhash, then give us a screenshot of fHash result.

**Comment by IAmBaconator** [comment]
Not sure if anyone else has come up again with version 1.2312 that just dropped last week.  I use the Plugin Admin from N++ to update/install plugins.

At first I made an attempt to simply update the version I was on.  It failed, I uninstalled the plugin and tried to install it, and it failed again.  Now I'm not able to use it anymore.

**Comment by chcg** [comment]
@IAmBaconator You could find the download location of the plugin at e.g. https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md (you need the matching list for your N++ platform x64, x86 or arm64) or see https://www.sunjw.us/jstool/npp/?ver=1.2312.0.0 . You could manually download it and put it into your N++ installation plugin folder.

For me there is no issue with the installation of the plugin from N++ 8.7.4 .

**Comment by IAmBaconator** [comment]
> @IAmBaconator You could find the download location of the plugin at e.g. https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md (you need the matching list for your N++ platform x64, x86 or arm64) or see https://www.sunjw.us/jstool/npp/?ver=1.2312.0.0 . You could manually download it and put it into your N++ installation plugin folder.
> 
> For me there is no issue with the installation of the plugin from N++ 8.7.4 .

Thank you!
