### ISSUE TITLE
不支持utf-8吗？格式化后中文显示的还是英文和数字字符。

### ISSUE THREAD

**Issue by yahuudang** [sunjw/jstoolnpp#77]
`{"status": 0, "prompts": "\u64cd\u4f5c\u6210\u529f", "data": [{"info": {"sub_brand_name": "KTM"}, "type": "1003"}, {"info": {"sub_brand_name": "KTM", "official_price_prefix": "\u6307\u5bfc\u4ef7\uff1a", "tags": [0, 0, 0], "color": 1, "business_status": 1, "concern_id": 25, "series_name": "X-BOW", "official_price": "139.00\u4e07", "series_id": 25, "dealer_inquiry_ab_v1": 2, "image_url": "https://p3.pstatp.com/large/w480/bef000009afa1b7652b7.png", "dealer_price": "", "motor_id": 1410000250000000, "dealer_tag": 0, "price": "139.00\u4e07"}, "type": "1002"}], "message": "success"}`

用Json Viewer可以正常格式化。

**Comment by sunjw** [comment]
格式化不会改变内容，不会做解码或者转义
