### ISSUE TITLE
Download links say "SourceForget.net"

### ISSUE THREAD

**Issue by AlexFolland** [sunjw/jstoolnpp#78]
I thought it was going to direct me to some sketchy site when I read the download link.  Luckily, it's not actually going somewhere called "sourceforget".  I see the author of this addon has typed "SourceForget" in various issues here on github, including https://github.com/sunjw/jstoolnpp/issues/55.  Maybe they actually think it has a "t" on the end.  It doesn't, since it's a place where you forge source.  It's not a place where you forget source.  "forge" and "forget" are very different words.

![image](https://user-images.githubusercontent.com/601517/66163807-0162c600-e5e6-11e9-9742-c4f64b15f632.png)

**Comment by sunjw** [comment]
Very thanks for reporting this. This is a big typo bug!
It will be fixed soon.

**Comment by sunjw** [comment]
Fixed in c11dbe39361854435e1d663453c2e17a89682cda
