### ISSUE TITLE
Creates incorrect code formatting specific minimized .js file

### ISSUE THREAD

**Issue by StephenWeatherford** [sunjw/jstoolnpp#81]
Nice extension, thanks...

1) In NotePad++, format the following code: https://gist.github.com/StephenWeatherford/c5baaf5624d85f959e97186fdc0d8407

This is from vscode insiders 1.41.0-insider (user setup)
Commit: 27cd33d891eb23e370b672e751be9fe8b3748ac1

C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js

2) Open the formatted code in vscode
!) There are quite a few syntax errors.  For example:
```
                        } catch (e) {
                            throw  / Please,
                             ? commit your changes or stash them / .test(e.stderr || "") && (e.gitErrorCode = "DirtyWorkTree"),
                            e
                        }
```
The original code looked like:
```
/Please,? commit your changes or stash them/.test(e)?"DirtyWorkTree":void 0}…
```

**Comment by sunjw** [comment]
Thanks for reporting this bug.
Seems a bug about regular expression. I'll check it.

**Comment by sunjw** [comment]
Fixed this issue and another related regular expression issue after de833628f576516c4c5beb80ab9540cc112e6c83

**Comment by StephenWeatherford** [comment]
Great, thanks!
