### ISSUE TITLE
Unescape JSON strings

### ISSUE THREAD

**Issue by PRMan99** [sunjw/jstoolnpp#82]
It would be great to have an option that removes backslash quote marks from escaped JSON strings.

The option could be called Unescape and would then make it ready for normal processing by the tool.

Example:

{\"Id\":\"235253\",\"Name\":\"John Smith\"}

Becomes:

{"Id":"235253","Name":"John Smith"}

**Comment by afischer-opentext-com** [comment]
I would appreciate this feature as well. It regularly happens that Json is dumped into log lines and an easy way to unescape the escaped Json would ease things a lot.

**Comment by sunjw** [comment]
@afischer-opentext-com try Visual Studio Code.

**Comment by afischer-opentext-com** [comment]
We should close this ticket s a wontfix then, if this is the answer to the request.
