### ISSUE TITLE
Syntax highlighting issue with Template Strings

### ISSUE THREAD

**Issue by mKainzbauer** [sunjw/jstoolnpp#85]
When template Strings (enclosed with Backticks "`") are used, syntax highlighting goes wrong:

![grafik](https://user-images.githubusercontent.com/58649043/71591058-230f1300-2b2b-11ea-91b7-7b86190dc5a2.png)

Line 283 to 292 is a Template String which isn't highlighted correctly.

**Comment by sunjw** [comment]
@mKainzbauer highlight is not part of JSTool, please submit this to [Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus)
