### ISSUE TITLE
Feature Request - Syntax Checking 

### ISSUE THREAD

**Issue by MacTheFork** [sunjw/jstoolnpp#86]
It would be helpful if this plugin would identify syntax errors in JSON.  Specifically, missing or trailing commas have caught me out several times.

So in this simple example it is formatted without any warning that there is a missing comma and a trailing comma.
{"elementkey": "elementvalue" 	"elementkey2": "element2value", }

**Comment by sunjw** [comment]
Hi @MacTheFork, I recommend you to use Visual Studio Code. VSC has built-in JSON syntax checking.

**Comment by MacTheFork** [comment]
Thanks for replying and confirming that VSC is the way forward.
