### ISSUE TITLE
Please add settings to configure default code highlight language

### ISSUE THREAD

**Issue by skironDotNet** [sunjw/jstoolnpp#89]
Previous versions defaulted to JavaScript, in the new version it default to JSON. I prefer JavaScript highlight, Can you add a config for this?

The scenario is I paste JSON into fresh opened n++ there is no highlight because it's in text mode.
I hit Ctrl + Alt + M and JSON data gets formatted, and Language switch to JSON (before JavasSript)

![image](https://user-images.githubusercontent.com/2981715/75903503-4a25e180-5e07-11ea-853d-ab650ee9643d.png)

I would really prefer this as default

![image](https://user-images.githubusercontent.com/2981715/75903863-d89a6300-5e07-11ea-9904-0a885a6a6e01.png)

See how null vs number is highlight? Also I prefer properties as gray

![image](https://user-images.githubusercontent.com/2981715/75903821-c4eefc80-5e07-11ea-8a72-ed3b4c59462f.png)

**Can you make it configurable?** 

Great plugin BTW!

Thank you!

**Comment by sunjw** [comment]
Related to #87

**Comment by skironDotNet** [comment]
Now I see that if you really can't enforce this, we should just reconfigure n++ ourselves. In style configuration we can select extension to language, or we could change style for JSON itself 
https://www.foxinfotech.in/2018/06/how-to-associate-a-file-type-with-language-in-notepad.html

**Comment by skironDotNet** [comment]
But there is no way to Delete JSON, or extension 
![image](https://user-images.githubusercontent.com/2981715/76555255-488e9600-6465-11ea-9d8e-bd95f9a685a2.png)

Also I just removed your plugin and npp still defaults to JSON language for .json extension, so may be a bug or other plugin issue. I'll keep positing here, chances are this not relevant to your plugin

**Comment by rapliu** [comment]
感谢中国制造，谢谢楼主，我要下载一个试试，从sourceforge发现此项目
