### ISSUE TITLE
New line is inserted after JSFormat

### ISSUE THREAD

**Issue by Valtarr** [sunjw/jstoolnpp#90]
If I use `JSFormat` functionality with `New line before '{'` enabled - it always inserts new line at the beginning of the file.
Can we change this - new line at the beginning of the file is not needed.

![image](https://user-images.githubusercontent.com/24985395/75965322-4fe7f980-5ed1-11ea-93c2-a136334b0342.png)

**Comment by Gaalidas** [comment]
I'd like to see this, and expanding the new line to include square brackets as well, in cases where the square brackets are followed by a multi-line block of information.  As a C# coder, I get really messed up seeing blocks of code with brackets on the same line as the object definition when the content is on a new line.

**Comment by sunjw** [comment]
Remove "new line before '{'" support.
