### ISSUE TITLE
Wrong regex formatting after multiplication symbol

### ISSUE THREAD

**Issue by Biotronic** [sunjw/jstoolnpp#92]
This may seem weird, but it's essentially converting a bool to a number:
```javascript
1*/a/.test("a")
```
When attempting to jsformat it, I get this:
```javascript
1 *  / a / .test("a")
```
The whitespace is all messed up, and the regex is no longer the same. If there are any escapes in there, there's basically no telling if the resulting code is going to do anything at all.

**Comment by sunjw** [comment]
Fixed in 3e4e9e44170fb30a6aebb2ade36e4993d4575cf6
