### ISSUE TITLE
Spaces between entities are minified

### ISSUE THREAD

**Issue by grenelt** [sunjw/jstoolnpp#96]
The whitespace after `&#xB0;`

`<button id="stepup_x" class="btn">+10&#xB0; &#x27F0;</button>`

is being removed by JSMin:

`<button id="stepup_x"class="btn">+10&#xB0;&#x27F0;</button>`

**Comment by sunjw** [comment]
Looks right to JSMin algorithm.

**Comment by grenelt** [comment]
Sorry, took me some time to understand. It's a kind of misusing, because i try to minify files with HTML and CSS code in it. That's because i'm messing arround with MCUs and try to have compact files.
But: JSMin removes trailing spaces after semicolons as intended, but doesn't know about the HTML tag. So i think the NP++ plugin should check and isolate the script tag before minifying with JSMin. I know - now it's more of a pull request... ;)
